project:
  type: book
  output-dir: _book

book:
  title: "R Programlama"
  author: 
    name: "Muhammed Fatih Tüzen"
    url: https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/
  reader-mode: true
  search: 
    location: navbar
    type: textbox
  page-footer:
    left: |
      &copy; 2023, [Muhammed Fatih Tüzen](https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/)
    right: |
      Bu kitap [Quarto](https://quarto.org/) ile hazırlanmıştır.
  cover-image: cover.png
  site-url: https://rprogramlama.netlify.app/
  repo-url: https://github.com/MFatihTuzen/r-book-tr
  repo-actions: [edit,issue]
  #page-navigation: true
  chapters:
    - index.qmd
    - r_about.qmd
    - part: R_intro.qmd
      chapters: 
        - basics.qmd
        - data_types.qmd
        - functions.qmd
        - if_else_for.qmd
        - date_time.qmd
        - strings.qmd
        - apply.qmd
        - import_export.qmd
    - data_manipulation.qmd
    - data_transformation.qmd
    - data_analysis.qmd
    - ggplot2.qmd
    - data_preprocess.qmd
    - statistics.qmd
    - regresyon.qmd

language: 
  title-block-author-single: "Yazar"
  toc-title-document: "İçindekiler"

format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

